services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge